# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

import sys

sys.path.append("/Workspace/Users/4botttt_gmail.com#ext#@4bottttgmail.onmicrosoft.com/New Pipeline 2025-10-31 12:54")

# COMMAND ----------

# !!! Before performing any data analysis, make sure to run the pipeline to materialize the sample datasets. The tables referenced in this notebook depend on that step.

display(spark.sql("SELECT * FROM spotify_catalog.gold.sample_trips_oct_31_1254"))

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT * FROM spotify_catalog.gold.dimuser;

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT * 
# MAGIC FROM spotify_catalog.gold.dimtrack
# MAGIC WHERE track_id in (46,5)

# COMMAND ----------

